### ISSUE TITLE
Requirements Elicitation on reviewing the SOW by Member (Krishnan)

### ISSUE THREAD

**Issue by Amitejashrout99** [marcandru/smarter-university-system#10]
This is an activity that is created for the purpose of completion of Epic #6 

In this Activity, as a member of the organization, @kiyer7 will go through the "Statement of the Work" document and list out the requirements that he feels the "SUS" software system needs considering the "Statement of the Work" document.

**Comment by Amitejashrout99** [comment]
@kiyer7, please create a separate task under this activity and label it as "Task". If the "Task" label doesn't exist, ask @marcandru to create one. After your analysis, post your requirements in the comment section.

**Comment by kiyer7** [comment]
Closing this activity on creating and completion of the task #41
