### ISSUE TITLE
Analyze the Elicited Requirements by Various Members and finding overlapping requirements

### ISSUE THREAD

**Issue by Amitejashrout99** [marcandru/smarter-university-system#12]
This is an Activity that is created for the purpose of completion of #6

In this activity, we as an organization will go through all the elicited requirements of all the members and find out the common overlapping requirements and discuss the validity of the elicited requirement.

**Comment by Amitejashrout99** [comment]
As a group; me , @marcandru and @sshidruk0721 have analyzed the elicited requirements and finalized on the overlapping elicited requirements. Will close this issue once @divyaratra19 and @kiyer7 have turned in their elicited requirements

**Comment by divyaratra19** [comment]
Closing this activity since we need to create separate activities for all individuals
