### ISSUE TITLE
Re-formulate the Requirements into User-Stories and group them on basis of similarity

### ISSUE THREAD

**Issue by Amitejashrout99** [marcandru/smarter-university-system#13]
This is an Activity that is created for the purpose of completion of #6

In this activity, we as an organization re-formulate the finalized requirements based on elicited requirements of each member and convert them into user-stories format that follow the format of "As a < type of user >, I want < some goal > so that < some reason >."
After creation of the User-Stories, each of the User-Story will be linked to a "Epic" that signifies the underlying similarity of a group of "User-Stories"

**Comment by Amitejashrout99** [comment]
@marcandru , In addition to creating a label for "Tasks", create another label for "Sub-Tasks". We might not need it but it's still better to be there.

**Comment by divyaratra19** [comment]
Closing this activity and creating new ones for each individual since everyone should be assigned an activity separately
