### ISSUE TITLE
Use-Cases Prioritization by Member (Divya)

### ISSUE THREAD

**Issue by Amitejashrout99** [marcandru/smarter-university-system#15]
This is an activity that is done for the purpose of the completion of Epic #14

In this Activity, as a member of the organization, @divyaratra19 will go through the "Use-Cases" listed out and create a Binary-Tree to elucidate her priority of the Use-Cases listed out. Once she has done so, she can also assign a numeric value to each of the "Use-Case" item in a excel sheet that is created to keep the status of the priority values of the "Use-Cases".

**Comment by Amitejashrout99** [comment]
Same as earlier, please create a new "Task" for each activity that you do and link it with it's parent activity issue. For ex, "creating a binary-tree" can be one task and "Updating priority values" could be another. Both of them are child activities/tasks of this activity and hence should be linked.

**Comment by divyaratra19** [comment]
Created binary tree and accordingly added the priority list to the sheet
