### ISSUE TITLE
Use-Cases Prioritization by Member (Krishnan)

### ISSUE THREAD

**Issue by Amitejashrout99** [marcandru/smarter-university-system#19]
This is an activity that is done for the purpose of the completion of Epic #14 

In this Activity, as a member of the organization, @kiyer7 will go through the "Use-Cases" listed out and create a Binary-Tree to elucidate his priority of the Use-Cases listed out. Once he has done so, he can also assign a numeric value to each of the "Use-Case" item in a excel sheet that is created to maintain the status of the priority values of the "Use-Cases".

**Comment by Amitejashrout99** [comment]
Same as earlier, please create a new "Task" for each activity that you do and link it with it's parent activity issue. For ex, "creating a binary-tree" can be one task and "Updating priority values" could be another. Both of them are child activities/tasks of this activity and hence should be linked.

**Comment by kiyer7** [comment]
Marking this activity as closed on completion of tasks #64 and #65
