### ISSUE TITLE
Creation of Protocols to be followed while creating Issues 

### ISSUE THREAD

**Issue by Amitejashrout99** [marcandru/smarter-university-system#2]
This is the first-epic created for the MVP #1 

As an organization, while creating Issues, proper protocols should be followed. The protocols that should be followed is different for each type of issue.
If the Issue if of type `Activities`, then the format should elucidate what the particular `Activity` does. Each `Activity` can have N number of issues of `Tasks` type which can be of various `label` category.
If the Task(Issue) is of type `User-Stories`, then the format should be "As a < type of user >, I want < some goal > so that < some reason >"
If the Task(Issue) is of type `Testing`, then the task should reflect the purpose of the Task  whether it be writing the unit test-cases or executing the Unit-Test cases
If the Task(Issue) is of  type `Analysis`, the the task should reflect exactly what the analysis is being done.

**Comment by marcandru** [comment]
I have created labels in #3 so if more are necessary we can reopen this
