### ISSUE TITLE
Writing Unit Test Cases to validate "SUS" Quiz Module Robustness

### ISSUE THREAD

**Issue by Amitejashrout99** [marcandru/smarter-university-system#23]
This is an Epic that is created for the purpose of completing the MVP #21

As a part of this epic, each member of the organization will attempt to test the robustness of the Quiz Module of the "SUS" software system by writing 3 test-cases that aim to break the API. Members should develop the test-case in such a way that each of their test cases makes the program crash. Additionally they should also ensure that failure should happen at different lines of the source code and not on the same line thereby ensuring more code-coverage during testing.

**Comment by marcandru** [comment]
Note, the requirements say a total of 3 unit tests should be made, so it is not necessary for each member to make 3

**Comment by Amitejashrout99** [comment]
Closing this Epic as all the activities linked to this Epic has been completed.
