### ISSUE TITLE
Creation of Issues Labels so that Issues can be tagged with appropriate Issue Tags. 

### ISSUE THREAD

**Issue by Amitejashrout99** [marcandru/smarter-university-system#3]
This is an activity that is created as a part of the Epic #2 

As an organization, Issue Labels should be created so that the type of each issue can be reflected properly to developers. For the purpose of "SUS", three labels have already been created by @marcandru. Based on further discussions, Labels will be added that accurately reflects the issue types.

Currently the Issue Labels are of Type:
Epic
MVP
Activity

**Comment by marcandru** [comment]
I have created three additional labels:
Testing
Analysis
Task

If wee need any additional ones we can just reopen this issue
