### ISSUE TITLE
Re-formulate the Requirements into User-Stories and group them on basis of similarity (Krishnan)

### ISSUE THREAD

**Issue by divyaratra19** [marcandru/smarter-university-system#31]
Duplicate of #13

This is an Activity that is created for the purpose of completion of EPIC #6 

In this activity, Krishnan needs to re-formulate the finalized requirements based on elicited requirements of each member and convert them into user-stories format that follow the format of "As a < type of user >, I want < some goal > so that < some reason >."
After creation of the User-Stories, each of the User-Story will be linked to an "Epic" that signifies the underlying similarity of a group of "User-Stories"

**Comment by kiyer7** [comment]
Marking this activity closed on completion of task #63
