### ISSUE TITLE
Re-formulate the Requirements into User-Stories and group them on basis of similarity (Amitejash)

### ISSUE THREAD

**Issue by divyaratra19** [marcandru/smarter-university-system#34]
Duplicate of #13 

This is an Activity that is created for the purpose of completion of EPIC #6

In this activity, Amitejash needs to re-formulate the finalized requirements based on elicited requirements of each member and convert them into user-stories format that follow the format of "As a < type of user >, I want < some goal > so that < some reason >."
After creation of the User-Stories, each of the User-Story will be linked to an "Epic" that signifies the underlying similarity of a group of "User-Stories"

**Comment by Amitejashrout99** [comment]
Closing this activity since the task #45 created as task for this story has been completed.
