### ISSUE TITLE
Analyze the Elicited Requirements by Various Members and finding overlapping requirements (Siddhi)

### ISSUE THREAD

**Issue by divyaratra19** [marcandru/smarter-university-system#39]
Duplicate of #12 

This is an Activity that is created for the purpose of completion of #6

In this activity, Siddhi will go through all the elicited requirements of all the members and find out the common overlapping requirements and discuss the validity of the elicited requirement.

**Comment by marcandru** [comment]
This is in relation to #26, which initially was assigned with two people, instead of one as specified in the project documents

**Comment by marcandru** [comment]
Here's the [document](https://docs.google.com/document/d/10GGlHO--ylQHnaPXtuK6gwRVfCBYcjkb4o1Z4NkCGOE/edit#heading=h.j344pbbpa7y2) for the final requirements

**Comment by sshidruk0721** [comment]
Closing this task in completion with #55
