### ISSUE TITLE
Creation of the Project Board in GitHub to appropriately represent the status of the issues

### ISSUE THREAD

**Issue by Amitejashrout99** [marcandru/smarter-university-system#4]
This is an epic that is created as a part of the MVP #1  

As an organization, we will be using the Project Board of the GitHub to keep track of all the Issues. At any-time the board will reflect the true status of the issues and would be the measure of the completion of the issues. 3-column format will be followed to  maintain the status of the project with the to-do reflecting the activities that are yet to be done; in-progress reflecting the activities that are in-progress and completed reflecting the stories that have been completed. Furthermore, essential permissions should be allocated to the collaborators so that they can change the status of the stories.

**Comment by marcandru** [comment]
I have created the project board for the SUS system and have added @Amitejashrout99 as an admin for the project board
