### ISSUE TITLE
Requirements Elicitation on reviewing the SOW by Member (Divya)

### ISSUE THREAD

**Issue by divyaratra19** [marcandru/smarter-university-system#40]
This is a task for Activity #7 

Need to come up with the Requirements after going through the Statement of work.

**Comment by divyaratra19** [comment]
After analysing the Statement of work, i found the following requirements separated by user roles:

Student:

- Allow students to sign up for classes  
- Display available classes and info (identifier of the class is as well as the title of the class, name of the lecturer with a link to the class syllabus page) to students
- Display unattended classes in the past after logging in
- Update class enrollment immediately when students register  
- Submission of an enrollment request to SUS (By student) 
- Support student teams and group assignments
- Track student grades and performance
- Enable grade visibility for students

Instructor:

- Allow syllabus updates throughout the semester (by instructor)
- Enable instructors to view enrolled students 
- Support student teams and group assignments
- Allow entry of grades for assignments, exams, quizzes
- Calculate grade statistics like average, high, low
- Enable grade visibility for instructors 

Admin:

- Track class enrollment and notify if near capacity
- Send email notification to the department administrators if a course is full
- Allow admins to view/add/drop students in closed classes
- Approve the enrollment request (By admin and instructor)
- Collect instructor information like education and courses

System:

- Support multiple class sections based on location
- Provide remote video access for distributed classes

**Comment by Amitejashrout99** [comment]
@divyaratra19 , could you please change the title of the task so as to reflect more about the activity that you did. For ex : Analyzing the SOW to find the requirements or something along those lines.
