### ISSUE TITLE
 Formulate Some User Stories and Add it to the Spreadsheet (Divya) 

### ISSUE THREAD

**Issue by marcandru** [marcandru/smarter-university-system#44]
Each member will grab some of the requirements from the document and turn it into a user story and add it to the spreadsheet. This is the issue for #30

**Comment by divyaratra19** [comment]
Added my user stories to spreadsheet

**Comment by divyaratra19** [comment]
digraph G {

  1->3
  1->2
  2->8
  2->9
  3->4
  3->6
  4->5
  4->R1
  5->L1
  5->12
  6->13
  6->7
  7->L2
  7->10
  8->16
  8->11
  9->21
  9->R4
  10->L3
  10->27
  11->24
  11->R5
  12->15
  12->R2
  15->18
  15->R3
  13->20
  13->14
  14->L4
  14->19
  16->17
  16->R6
  17->25
  17->28
  21->23
  21->22
  22->L5
  22->30
  25->L6
  25->26
  28->L7
  28->29
  30->31
  30->32
  32->L8
  32->33
}
