### ISSUE TITLE
Formulate Some User Stories and Add it to the Spreadsheet (Amitejash)

### ISSUE THREAD

**Issue by marcandru** [marcandru/smarter-university-system#45]
Each member will grab some of the requirements from the document and turn it into a user story and add it to the spreadsheet. This is the task for #34

**Comment by Amitejashrout99** [comment]
Requirements assigned to me by @kiyer7 as part of #57 has been completed and placed in the spreadsheet created in #16. Closing this task as closed and further closing the parent issue #34 also as closed
