### ISSUE TITLE
Formulate Some User Stories and Add it to the Spreadsheet (Krishnan)

### ISSUE THREAD

**Issue by marcandru** [marcandru/smarter-university-system#47]
Each member will grab some of the requirements from the document and turn it into a user story and add it to the spreadsheet. This is the issue for #31

**Comment by kiyer7** [comment]
Created the user stories and assigned the epics in #63

**Comment by kiyer7** [comment]
CLosing this actvity has completed since the user stories are added to the spreadsheet in #16 .
