### ISSUE TITLE
Create Unit Tests for Quality Assurance (Marc)

### ISSUE THREAD

**Issue by kiyer7** [marcandru/smarter-university-system#68]
This is an activity that is created for the purpose of completion of the epic https://github.com/marcandru/smarter-university-system/issues/23.

In this activity @marcandru is tasked to create unit cases test to cause such an application failure. The focus shall be set on the quizzes module.

**Comment by marcandru** [comment]
The unit test cases have been created and verified in the pull request to the main branch of the fork, and another pull request has been made to the origin SUS repo.
