### ISSUE TITLE
Create API Test Inputs for Quality Assurance (Divya)

### ISSUE THREAD

**Issue by kiyer7** [marcandru/smarter-university-system#69]
This is an activity that is created for the purpose of completion of the epic https://github.com/marcandru/smarter-university-system/issues/22 and activity https://github.com/marcandru/smarter-university-system/issues/24

In this activity @divyaratra19 is tasked to create test inputs for an API endpoint. Her task is to create test cases that are effective in uncovering defects using the category partition and boundary analysis methods.

Goals
- To mimic both nominal use and invalid use of the API endpoint (That is, to specify test cases where the values of parameters adhere to the specified constraints)
- Specify test cases that slightly deviate from the format but may be reasonably considered valid from a common sense perspective
- Provide values that are clearly outside the specified format

Input Parameters for the API Test Inputs could be referred from Page 10 of the document - 
[ENPM611 Project Assignment.pdf](https://github.com/marcandru/smarter-university-system/files/13359828/ENPM611.Project.Assignment.pdf)

**Comment by divyaratra19** [comment]
I have added the values for my assigned parameters (recipients and post_time) to the sheet
