### ISSUE TITLE
Requirements Elicitation by Member based on SOW (Divya)

### ISSUE THREAD

**Issue by Amitejashrout99** [marcandru/smarter-university-system#7]
This is an activity that is created for the purpose of completion of Epic #6

In this Activity, as  a member of the organization, @divyaratra19 will go through the "Statement of the Work" document and list out the requirements that she feels the "SUS" software system needs considering the "Statement of the Work" document

**Comment by Amitejashrout99** [comment]
@divyaratra19 , please create a separate task under this activity and label as "Task". If the "Task" label doesn't exist, ask @marcandru  to create one. After your analysis, post your requirements in the comment section.

**Comment by Amitejashrout99** [comment]
@marcandru please create a Label for Task if it doesn't exist in the Labels.

**Comment by marcandru** [comment]
@Amitejashrout99 I made the task label earlier this week iirc

**Comment by divyaratra19** [comment]
Marking this activity as closed on completion of Task #40
