### ISSUE TITLE
Requirements Elicitation on reviewing the SOW by Member (Marc)

### ISSUE THREAD

**Issue by Amitejashrout99** [marcandru/smarter-university-system#9]
This is an activity that is created for the purpose of completion of Epic #6 
In this Activity, as a member of the organization, @marcandru will go through the "Statement of the Work" document and list out the requirements that he feels the "SUS" software system needs considering the "Statement of the Work" document

**Comment by Amitejashrout99** [comment]
@marcandru, please create a separate task under this activity and label it as "Task". If the "Task" label doesn't exist, please create one so that it can be used by the others as well. After your analysis, post your requirements in the comment section.

**Comment by marcandru** [comment]
Here are my requirements, separated into four different categories:

Student should be able to:
- sign up for available classes
- find classes
- see classes not taken
- submit enrollment requests
- see members in groups they're assigned to
- see their own grades

Instructors/TAs should be able to:
- Modify their syllabus and maintain it throughout the semester
- approve enrollment requests
- access the list of students for each class they are teaching
- assign groups
- enter grades in bulk or individually
- see the average, highest, lowest, and individual grades for students

Administrator should be able to:
- be notified when enrollment is 80%
- see status of courses, such as the number of students enrolled currently, and the max amount of students that can enroll in the class
- add or remove students from classes
- find information about the instructors, such as their name, email, previously taught courses, as well as their education. _For education, they should also be able to see their highest degree earned, the institution they went to, and their year of graduation_

The system should be able to:
- Label classes with their id plus their title, the name of the instructor, and a link to the syllabus
- The syllabus page should contain the date of each lecture and the topic for the lecture
- There should be a database for the grades. _The database should be secure_
- There should also be databases for information about the admins/instructors/students. _Also should be secure_
- Determine _availability_ of classes, such as whether or not a class has exceeded the amount of people enrolled in it
